### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by maxduke** [marcellourbani/vscode_abap_remote_fs#30]
Hello,

I got the issue "unable to get local issuer certificate" when trying to connect to ABAP system. Could you please help? Thanks.

Regards,
Duke

**Comment by marcellourbani** [comment]
Should be a certificate issue.
You're trying to access over HTTPS, but the certificate is self-signed (or signed by a corporate entity not recognized by vscode )

If it's that, all I can do make the error more user friendly.

You can probably get it to work installing some certificate (your root CA or the site certificate) in vs code or the system. See the SSL section of [this document](https://code.visualstudio.com/docs/setup/network)

**Comment by marcellourbani** [comment]
Almost forgot. If that's the issue, opening that URL in your browser should give you an error about the insecure certificate before you even get to a login page

**Comment by rayatus** [comment]
I have the same problem and yes, when opening URL from browser it shows a security warning.
I'm trying to test VSCode with my NPL Developer Trial 7.5, how can I configure SAP in order to issue a correct certificate?

**Comment by marcellourbani** [comment]
This [blog entry](https://blogs.sap.com/2018/12/13/use-a-lets-encrypt-certificate-for-sap-hana-or-sap-netweaver-as-abap/) from Gregor Wolf explains how to get a free certificate

If you use it locally it's probably easier to just use HTTP, which is what I do.

**Comment by maxduke** [comment]
Thanks for the info. I tried to access the URL in the browser, but without an SSL cetificate error. I'm wondering if I specifed the correct port number in the user settings JSON. Currently I used the port number defined in SICF. Is that correct?

**Comment by marcellourbani** [comment]
@maxduke
What works in the browser should work in the extension. 
The only partial exception is SSL: chrome, vscode and others use the system certificates, i reckon Firefox has its own store.

Also some allows you to store permanent exceptions: you still see the certificate is invalid if you look at it, but the browser just ignores it. 

Is that your own server or some corporate one? 
Does it have a public URL? In case can you send it to me?

**Comment by maxduke** [comment]
@marcellourbani 
The server is corporate one and coporate SSL cetificate is installed in system. I can access that w/o SSL certificate error in both IE and Chrome.
One question regarding the URL, how can I check if I specify the correct port number? Where can I find the the port number? Currently I used the port number in SICF.(by testing service)

**Comment by marcellourbani** [comment]
If it works in chrome it's the right port. For SSL I need to look into it

**Comment by marcellourbani** [comment]
funnily enough also works with my newly installed 7.52 abap trial, whose certificate gets rejected by chrome...

**Comment by Xempai** [comment]
Hello,

I'm getting the error on the extension but not on chrome , is there a way to ignore the certificate check ? 

Or retreive the CA certificate and make it trusted by Visual Studio Code ? 

Thanks & Regards,
Youssef

**Comment by rayatus** [comment]
@marcellourbani, as per your comment... 

> This [blog entry](https://blogs.sap.com/2018/12/13/use-a-lets-encrypt-certificate-for-sap-hana-or-sap-netweaver-as-abap/) from Gregor Wolf explains how to get a free certificate
> 
> If you use it locally it's probably easier to just use HTTP, which is what I do.

you suggested switching to HTTP, but I'm not able to change to HTTP. Well for sure I'm doing something wrong.

As per my SMICM services, HTTP is listening in port 80000 (I don't know why are 2 different ports)

![image](https://user-images.githubusercontent.com/12736990/51792018-2461ee00-21ac-11e9-8e27-6d6170d14b96.png)

I suppossed that if I can access Fiori launchpad throug https://vhcalnplci:44300/sap/bc/ui2/flp I could do that with http://vhcalnplci:8000/sap/bc/ui2/flp, so I changed extension URL to http://vhcalnplci:8000, but If I try to access to launchpad via URL http://vhcalnplci:8000/sap/bc/ui2/flp it finishes with TimeOut, so definetly I'm wrong.

How can I change to HTTP?

**Comment by marcellourbani** [comment]
@Xempai  there must be one, as my installation happily sucks unsigned  certificates!
Will definitely look into it whenever I find the time, but not today

BTW, I just realised that since I use an off-the-shelf library to do HTTP it might not work the same as code

**Comment by i042416** [comment]
Hello Marcellourbani,

first of all you did a very good job! 

My Netweaver ABAP server is located in the corporate network and I can only access it via https: 

I tried all approaches currently found in the internet to avoid this annoying issue but does not work.

Looking forward to your investigation!

Best regards,
Jerry

**Comment by marcellourbani** [comment]
Good point, I will add code to honor that @i042416

**Comment by marcellourbani** [comment]
I just created a new build with 2 additional parameters:

- allowSelfSigned to accept self signed SSL certificates
- customCA to set the root CA's certificate

Was only able to test the first one though

It's not on the market yet, but you can download it from [here](https://github.com/marcellourbani/vscode_abap_remote_fs/releases/download/0.3.6/vscode-abap-remote-fs-0.3.6.vsix)

**Comment by marcellourbani** [comment]
PS: the reason why I didn't release it yet is that I know it to be buggy, it's in the middle of refactoring to the new API

**Comment by marcellourbani** [comment]
Ok guys, I just released an "official" update on the vscode marketplace which should fix this.
Waiting for your feedback!

**Comment by maxduke** [comment]
Thanks for the update. I've updated that to version 0.4.1, but the same issue still occurs.  @i042416 I'm wondering if the fix works for you.

**Comment by i042416** [comment]
@maxduke  same here, unfortunately the issue still persists in version 0.4.1:

![image](https://user-images.githubusercontent.com/5669954/52544409-c3612980-2deb-11e9-95f4-b3167d1cffec.png)

![image](https://user-images.githubusercontent.com/5669954/52544455-d2e07280-2deb-11e9-8a44-4fa5c0f298a6.png)

**Comment by marcellourbani** [comment]
@maxduke  @i042416 Did you set parameter allowSelfSigned to true?
![image](https://user-images.githubusercontent.com/2453277/52548661-e1686300-2dc6-11e9-8733-94eb09c5ee4f.png)

btw, that reload button means you're still using the previous version.

**Comment by marcellourbani** [comment]
@i042416 Almost forgot: I didn't support the parameter you mentioned above because it's about proxies.
So far I just try to connect directly, ignoring vscode's and system's proxy setting.

Not sure whether the system does that for me or not, I didn't try it.

**Comment by maxduke** [comment]
I tested with that parameter but it with no luck.

**Comment by marcellourbani** [comment]
Did you try customCA too? It's supposed to be assigned the root CA certificate from your organization.
I didn't try it myself though for lack of a suitable system.

PS: if your URL is accessible from outside I would like to have a look. Don't need a login to test this as it's all about connection layer

**Comment by maxduke** [comment]
No, I can see some root CA certificates are installled in the system and one of them is the organization one.
Unfortunately mine is an internal URL.

**Comment by i042416** [comment]
Hi Marcellourbani,

Thanks a lot for your updating on version 0.4.1. After I updated to this version and use parameter  "allowSelfSigned": true, your nice extension would connect my internal system successfully, that's great!

Unforunately, I still meet with 404 error as below.

![image](https://user-images.githubusercontent.com/5669954/52843896-5b3d7b00-313e-11e9-98ca-742d5eb0807f.png)

Here below is my settings.json:
![image](https://user-images.githubusercontent.com/5669954/52844012-993a9f00-313e-11e9-9e8b-981853a9c0bb.png)

The ADT service in my system is active and works well - I could use ABAP development tool to manipulate this system perfectly.

When I choose "Test Service" on this service in tcode SICF:
![image](https://user-images.githubusercontent.com/5669954/52844088-c6874d00-313e-11e9-8c9e-81748f529fbb.png)

I see 404 error as well.
![image](https://user-images.githubusercontent.com/5669954/52844136-e3238500-313e-11e9-9c1b-bc2407798bea.png)

So simply speaking, I am confused that what exact url should I maintain in settings.json?

Thanks a lot for @marcellourbani   's kind help so far and look forward to your reply!

Best regards,
Jerry

**Comment by marcellourbani** [comment]
@i042416
You should remove the path from your configuration

**Comment by marcellourbani** [comment]
@maxduke 
Yesterday I created my own ca and spent quite a bit on this with puzzling results:

- I validated the NPM library is working on its own
- it doesn't inside the extension!
- it was working in my system because another extension disabled the checks

On the plus side, you can use that as a workaround: set environment variable NODE_TLS_REJECT_UNAUTHORIZED to 0 (warning: it's not generally a good idea, better do it only for this, like in a batch file to launch code)
or install and configure [settings-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) and let it do it for you

**Comment by marcellourbani** [comment]
@maxduke 
I finally got this working for real.
Doesn't seem to accept system certificates automatically, but you can now specify your own customCA or simply set 'allowSelfSigned to true
